# This file was generated by GoReleaser. DO NOT EDIT.
class Cgit < Formula
  desc "cgit is a tiny tool for Chinese developers."
  homepage "https://github.com/linuxsuren/cgit"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.4/cgit-darwin-amd64.tar.gz"
    sha256 "2a167739fb702307b22cb3e457c252f0a523e6829650a48b558d67c10c94745c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.4/cgit-linux-amd64.tar.gz"
    sha256 "a6348977951b8dca71fff7fb1339acef8b3091e4993e04ca9fa398bcf64fb5fd"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.4/cgit-linux-arm64.tar.gz"
    sha256 "a5787053c16e09cf01f3daec11c6dda72a79c228e33859cae1ef478deb1aa250"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/cgit version")
    assert_match version.to_s, version_output
  end
end
