# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgit < Formula
  desc "cgit is a tiny tool for Chinese developers."
  homepage "https://github.com/linuxsuren/cgit"
  version "0.0.9"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.9/cgit-darwin-amd64.tar.gz"
    sha256 "3e81f4f2dc440cc47e709848141afc7d514426a52d4a0761294b53b8acb1af9e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.9/cgit-linux-amd64.tar.gz"
    sha256 "00aeeb82103fbd700aeee6ef0e161ab836a02ef395babf7f2e123868bd34167c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.9/cgit-linux-arm64.tar.gz"
    sha256 "a28a34e970d45a861e8c3880c07c20affb00712ca150d9570cc9e6d26ac07b4b"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/cgit version")
    assert_match version.to_s, version_output
  end
end
