# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgit < Formula
  desc "cgit is a tiny tool for Chinese developers."
  homepage "https://github.com/linuxsuren/cgit"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.13/cgit-darwin-amd64.tar.gz"
      sha256 "346057fe11bc0e964b0599e5743ccc7c8ba7d51d4e1022d9683d6994b071e0d4"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.13/cgit-darwin-arm64.tar.gz"
      sha256 "10a3756fe4e826f6917198f581d1eb14fd06ad650d9d10c39776e29cdc1d28b0"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.13/cgit-linux-arm64.tar.gz"
      sha256 "cd9e43fc821fd7e14933aa1181a0b930106579d0a723e5991fccb061f1d37fb1"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/cgit/releases/download/v0.0.13/cgit-linux-amd64.tar.gz"
      sha256 "b080080a83e7f6ecb1c60b3c7b7ab86e4b720ee9705918da39a148a84da598bc"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  test do
    version_output = shell_output("#{bin}/cgit version")
    assert_match version.to_s, version_output
  end
end
