# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ga < Formula
  desc "ga is a tiny tool for alias your CLI."
  homepage "https://github.com/linuxsuren/go-cli-alias"
  version "0.0.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/go-cli-alias/releases/download/v0.0.6/ga-darwin-amd64.tar.gz"
    sha256 "37cbf0b302b9b7f0da7b51ad3c0df9b89f83248e88b159d16a3048e922cb37e7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/go-cli-alias/releases/download/v0.0.6/ga-linux-amd64.tar.gz"
    sha256 "983c17d405e14d290775e9c14c53f90694b449097fce38e4c52d668c545ab4d3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/go-cli-alias/releases/download/v0.0.6/ga-linux-arm64.tar.gz"
    sha256 "8a6e8f887e6de04629a5820865a3480011b1d78a975c4e1e7cc5dd8f29f65042"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/ga version")
    assert_match version.to_s, version_output
  end
end
