# This file was generated by GoReleaser. DO NOT EDIT.
class Ga < Formula
  desc "ga is a tiny tool for alias your CLI."
  homepage "https://github.com/linuxsuren/go-cli-alias"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LinuxSuRen/go-cli-alias/releases/download/v0.0.3/ga-darwin-amd64.tar.gz"
    sha256 "45bcdb0106280c69c7f509346318810f6e81746e1ec81a0c91607418ae02956d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/go-cli-alias/releases/download/v0.0.3/ga-linux-amd64.tar.gz"
    sha256 "223ece817b2307689391ac489c8de99b44ef0b371147553cad547d8ec5250809"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/go-cli-alias/releases/download/v0.0.3/ga-linux-arm64.tar.gz"
    sha256 "e0d10c13dc631ba2c8be6cf9bed8361bfc4645389aff649a1631d70209260acd"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/ga version")
    assert_match version.to_s, version_output
  end
end
