# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hd < Formula
  desc "HTTP download tool"
  homepage "https://github.com/linuxsuren/http-downloader"
  version "0.0.51"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.51/hd-darwin-arm64.tar.gz"
      sha256 "fd7cddceb5d03c61c8571b2d2c41b978511f143c3d91561372559dd5f490a2b0"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.51/hd-darwin-amd64.tar.gz"
      sha256 "9e0ff231070a964c6a0f7f75c3a9551114230a7b54e6c48c924498db3ee9bcfb"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.51/hd-linux-arm64.tar.gz"
      sha256 "62d7ff0e2faa8e396aba6b1b185b99d008c4cbe85d291c8a8cd75d66878acd58"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.51/hd-linux-amd64.tar.gz"
      sha256 "9657c537890ab4b592c8550d76ed9f294d15d3dcee28e7f3e6d49b02bf9da8d9"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  depends_on "bash-completion" => :optional

  test do
    version_output = shell_output("#{bin}/hd version")
    assert_match version.to_s, version_output
  end
end
