# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hd < Formula
  desc "HTTP download tool"
  homepage "https://github.com/linuxsuren/http-downloader"
  version "0.0.30"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.30/hd-darwin-amd64.tar.gz"
      sha256 "2a3cac6556cf7c2eed00f9d0e8772495d10aa17011540df0cd6fdfec50147282"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.30/hd-linux-amd64.tar.gz"
      sha256 "9841f70f06c6b67bd5ec14f7ecab4684ae74ee426ec0c999cec9deb424462661"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.30/hd-linux-arm64.tar.gz"
      sha256 "513ee672dea7693f4a3fd18acbafcf5c97bc728f23e1820e1f2ec04f3f6b5d39"
    end
  end

  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/hd version")
    assert_match version.to_s, version_output
  end
end
