# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hd < Formula
  desc "HTTP download tool"
  homepage "https://github.com/linuxsuren/http-downloader"
  version "0.0.81"

  depends_on "bash-completion" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.81/hd-darwin-amd64.tar.gz"
      sha256 "d89988e5f72919057b0a4c4462267f88c2492ad47c95454bbaaf019b494756b8"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.81/hd-darwin-arm64.tar.gz"
      sha256 "8ade087c2ac3c32b5897594c89de9f31dc508bbbda5d5a7381b993a4db90aacd"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.81/hd-linux-arm64.tar.gz"
      sha256 "a2a83d5ee5f98f72cac8c99899c4be88764f76ccf2b2c18e39cb6dde9e2b0179"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.81/hd-linux-arm6.tar.gz"
      sha256 "6a0a7e2c97f1933aa00a5faa814fb859d84f54aa2112ba34633ca8f1506fa661"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.81/hd-linux-amd64.tar.gz"
      sha256 "6655cab1a811dd3e5639714126ac24871f43c5b8c98e508a948efa334b7d3d39"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/hd version")
    assert_match version.to_s, version_output
  end
end
