# This file was generated by GoReleaser. DO NOT EDIT.
class HttpDownloader < Formula
  desc "cgit is a tiny tool for Chinese developers."
  homepage "https://github.com/linuxsuren/http-downloader"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.2/http-downloader-darwin-amd64.tar.gz"
    sha256 "bb919ec9a9540f2a4120dfa04571a2e937f69278e434a80a2fe07d1ecaace18b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.2/http-downloader-linux-amd64.tar.gz"
    sha256 "456ab0549093456ab6194dacff8ed30a94b032887b1a3e3a0186b2bdc73129f8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.2/http-downloader-linux-arm64.tar.gz"
    sha256 "b0f768cf9427461077716d4729d424cf31c7248d55fe26b11178c7da1171cb05"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/http-downloader version")
    assert_match version.to_s, version_output
  end
end
