# This file was generated by GoReleaser. DO NOT EDIT.
class HttpDownloader < Formula
  desc "cgit is a tiny tool for Chinese developers."
  homepage "https://github.com/linuxsuren/http-downloader"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.1/http-downloader-darwin-amd64.tar.gz"
    sha256 "e3661ca5a5ca59a3a879b8f5954873594c3560972a32096d5529a6e48e8eff4a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.1/http-downloader-linux-amd64.tar.gz"
    sha256 "1eca2e2c285f47ee04b008207846082ef73ec862970eab8fe726b76022aed00b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/http-downloader/releases/download/v0.0.1/http-downloader-linux-arm64.tar.gz"
    sha256 "085ba664f6d8bb5a2d3319fe7df7fa2618c84f9a2e0a6360ecf9f51732de868f"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/http-downloader version")
    assert_match version.to_s, version_output
  end
end
