# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JcliKsPlugin < Formula
  desc "cgit is a tiny tool for Chinese developers."
  homepage "https://github.com/linuxsuren/jcli-ks-plugin"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/jcli-ks-plugin/releases/download/v0.0.2/jcli-ks-plugin-darwin-amd64.tar.gz"
    sha256 "43f96cce3f25703a46180b83a2c6b7012f4f29a349eea07d5dbec494603548b3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LinuxSuRen/jcli-ks-plugin/releases/download/v0.0.2/jcli-ks-plugin-linux-amd64.tar.gz"
    sha256 "d7f0c99c2e3a98f2e898c6a27ccef0742e6623e3b03ce8b8f917cad13c746969"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LinuxSuRen/jcli-ks-plugin/releases/download/v0.0.2/jcli-ks-plugin-linux-arm64.tar.gz"
    sha256 "4d99c4cc511c7087b0ea9ad31ee52456692435b803f65e01471a2d78d0ccbca5"
  end

  depends_on "vim" => :optional
  depends_on "bash-completion" => :optional

  def install
    bin.install name

    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/jcli-ks-plugin version")
    assert_match version.to_s, version_output
  end
end
