# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp < Formula
  desc "image mirror pull tool"
  homepage "https://github.com/linuxsuren/mirrors"
  version "0.0.4"

  depends_on "bash-completion" => :optional

  on_macos do
    url "https://github.com/LinuxSuRen/mirrors/releases/download/v0.0.4/mp-darwin-amd64.tar.gz"
    sha256 "8c99aaa8d1cbdb6cf093d7b112404a33841657c8876a063bf6f983d7628cdf0d"

    def install
      bin.install name

      prefix.install_metafiles
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/mirrors/releases/download/v0.0.4/mp-linux-amd64.tar.gz"
      sha256 "6e1038d1b81afc6f03fdb7814dcdbbf70a46f3cc0b08cb4fe712348055e5c8cd"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/mp version")
    assert_match version.to_s, version_output
  end
end
