# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mp < Formula
  desc "image mirror pull tool"
  homepage "https://github.com/linuxsuren/mirrors"
  version "0.0.6"

  depends_on "bash-completion" => :optional

  on_macos do
    url "https://github.com/LinuxSuRen/mirrors/releases/download/v0.0.6/mp-darwin-amd64.tar.gz"
    sha256 "0113cd7c1041338fbae324002a1999937fcf492e4253529726347e9a3d3e763f"

    def install
      bin.install name

      prefix.install_metafiles
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/mirrors/releases/download/v0.0.6/mp-linux-amd64.tar.gz"
      sha256 "3894e911f637b483482b39fafc7d81594c473f6415d21aa797f60656280f7cd1"

      def install
        bin.install name

        prefix.install_metafiles
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/mp version")
    assert_match version.to_s, version_output
  end
end
